#ifndef  __DISHANVESHI_INCLUDED_DSVI_BITMAP_DEFS_H__
#define  __DISHANVESHI_INCLUDED_DSVI_BITMAP_DEFS_H__

#define BITMAP_COMBINED_HEADER_SIZE 62

#if BITMAP_COMBINED_HEADER_SIZE < 62
#define BITMAP_COMBINED_HEADER_SIZE 62
#endif

#define DSVI_IMAGE_BMP_FILE_HEADER_SIZE 14

#define DSVI_BITMAP_SIGNATURE "BM"
#define DSVI_BITMAP_RESERVED 0
#define DSVI_BITMAP_INFOHEADER_SIZE 40
#define DSVI_BITMAP_PLANES 0
#define DSVI_BITMAP_X_PIX_PER_M 0
#define DSVI_BITMAP_Y_PIX_PER_M 0
#define DSVI_BITMAP_COMPRESSION 0
#define DSVI_BITMAP_IMP_COLORS  0

#define DSVI_BITMAP_OFFSET_FILEHEADER 0
#define DSVI_BITMAP_OFFSET_INFOHEADER 0x0E

// FILE HEADER (FHDR)
#define DSVI_BITMAP_OFFSET_FHDR_SIGNATURE  0x00
#define DSVI_BITMAP_OFFSET_FHDR_FILESIZE   0x02
#define DSVI_BITMAP_OFFSET_FHDR_RESERVED   0x06
#define DSVI_BITMAP_OFFSET_FHDR_DATAOFFSET 0x0A

// INFO HEADER (IHDR)
#define DSVI_BITMAP_OFFSET_IHDR_SIZE          0x0E
#define DSVI_BITMAP_OFFSET_IHDR_WIDTH         0x12
#define DSVI_BITMAP_OFFSET_IHDR_HEIGHT        0x16
#define DSVI_BITMAP_OFFSET_IHDR_PLANES        0x1A
#define DSVI_BITMAP_OFFSET_IHDR_BITSPERPIXEL  0x1C
#define DSVI_BITMAP_OFFSET_IHDR_COMPRESSION   0x1E
#define DSVI_BITMAP_OFFSET_IHDR_IMAGESIZE     0x22
#define DSVI_BITMAP_OFFSET_IHDR_XPIXPERM      0x26
#define DSVI_BITMAP_OFFSET_IHDR_YPIXPERM      0x2A
#define DSVI_BITMAP_OFFSET_IHDR_COLORSUSED    0x2E
#define DSVI_BITMAP_OFFSET_IHDR_IMPCOLORS     0x32
#define DSVI_BITMAP_OFFSET_IHDR_COLORTABLE    0x3E

#endif // __DISHANVESHI_INCLUDED_DSVI_BITMAP_DEFS_H__
