#ifndef __DISHANVESHI_INCLUDED_DSVI_IMAGE_OPERATIONS_DEFS_H__
#define __DISHANVESHI_INCLUDED_DSVI_IMAGE_OPERATIONS_DEFS_H__

#include <dishanveshi/defs.h>


#define DSVI_HISTOGRAM_ABS_MIN 0
#define DSVI_HISTOGRAM_ABS_MAX 255
//
#ifdef  DSVI_CONFIG_PUBLIC_HISTOGRAM
#define DSVI_PUBLIC_HISTOGRAM 1
#undef  DSVI_CONFIG_PUBLIC_HISTOGRAM
#else
#define DSVI_PUBLIC_HISTOGRAM 0
#endif

#endif // __DISHANVESHI_INCLUDED_DSVI_IMAGE_OPERATIONS_DEFS_H__
